Repository edenlabllc/rmk, pull requests merged in 2024-06, with the labels that each got.

#5 Improve and restructure documentation globally. Add docs/configuratio…
  README.md
  docs/commands.md
  docs/configuration/cluster-management/cluster-management.md
  docs/configuration/cluster-management/exported-environment-variables.md
  docs/configuration/project-management/dependencies-management-and-project-inheritance.md
  docs/configuration/project-management/preparation-of-project-repository.md
  docs/configuration/project-management/requirement-for-project-repository.md
  docs/configuration/release-management/release-management.md
  docs/configuration/rmk-configuration-management.md
  docs/configuration/secrets-management/secrets-management.md
  docs/development-and-release-flow.md
  docs/quickstart.md
  docs/release-notes.md
Labels: documentation

#9 #8 - Improve RMK context switch documentation.
  README.md
  commands/project_generation_category.go
  docs/configuration/cluster-management/cluster-management.md
  docs/configuration/rmk-configuration-management.md
  docs/configuration/secrets-management/secrets-management.md
Labels: documentation

#10 Improve documentation for cluster switch depending on an RMK cluster …
  docs/release-notes.md
Labels: documentation

#14 Improve documentation for cluster switch conflicts in K8S contexts.
  commands/download_packages.go
  docs/configuration/cluster-management/cluster-management.md
Labels: bug, documentation

#16 Feature/rmk 12 rmk cluster switch k8s context selection logic should be more strict
  commands/release_category.go
  docs/release-notes.md
Labels: bug
